### ISSUE TITLE
Add command prefix

### ISSUE THREAD

**Issue by ghost** [ace3df/AcePictureBot#101]
IDEA - Discord

The bot only needs a word to call a function (e.g. "waifu", "trap" or "harem").

Could be useful to add a prefix so that the bot doesn't reply to random messages (for example when people are debating about their waifus). 

I didn't see any closed issue referring this but if someone already asked, feel free to close this issue, if you don't have time to work on this fix, I can probably submit a pull request once I have some free time.

**Comment by ace3df** [comment]
There wont be a prefix for normal commands, you can either do:
!apb settings whitelist #channel_name
or
A prefix itself could be you making users have to @ mention the bot using:
!apb settings mention

This will make more users have to "[at]acepicturebot waifu" to trigger it etc.

You can read a bit more on "!apb settings" here:

https://acepicturebot.com/wiki/discord-settings

**Comment by ghost** [comment]
Thanks for the reply,

I think the mention setting is the best option I have since I want the bot to be usable in any channel (just in case). 

I thing you can close this issue now since you basically answered my question.
