### ISSUE TITLE
Can't register

### ISSUE THREAD

**Issue by Nongwin** [ace3df/AcePictureBot#68]
(DISCORD) Had Yato from Noragami as myhusbando and Mirai from Kyoukai no kanata as mywaifu, but when I joined a new server with the bot, I kept getting the message where it told me I had to register them again, even though it worked fine on the other server. Tried re-registering them, didn't work. The bot just kept tweeting random pics of husbandos/waifus instead of registering.

**Comment by ace3df** [comment]
> The bot just kept tweeting random pics of husbandos/waifus instead of registering.

Huge chance you're using the command wrong.

Please read the examples[ listed here](http://ace3df.github.io/AcePictureBot/commands/)

**Comment by Nongwin** [comment]
https://gyazo.com/eedb71bcc19e90619389057fe16b716d <-- the tweet + reply that I got
https://gyazo.com/ef9bc401a5329ce33ee49c683e17259d <-- the waifu on the waifu list
https://gyazo.com/90f590d70bb4e7519c5cddfd1a6ec12d <-- husbandoregister
https://gyazo.com/00c87408e857a9f4f7440bbfcb29a959 <-- husbandoregister without anime name

edit: tried mywaifu/myhusbando on discord after those attempts to register, didn't work.

**Comment by ace3df** [comment]
The examples show that you don't include the anime name unless it's a single name/the first column in the waifu/husbando file uses it, so the first 3 images are wrong on your end. 

Did you already have a waifu/husbando linked to your Discord account? Suddenly linking your other Twitter account can cause problems (and shouldn't really be done in the first place).

**Comment by Nongwin** [comment]
Yes, like I said on the first comment, I did have a waifu/husbando linked to my discord account. However, when I joined another discord server with the bot, the commands stopped working. It kept telling me that I haven't registered a mywaifu/myhusbando, so I tried doing it again. That didn't work, so I tried with a different twitter account.

**Comment by ace3df** [comment]
As I said having two accounts connected will cause problems.

Twitter ids: 1357835971 and 1364533530 (1364533530 being the one in the images).

I removed 971 so it should work now.
