### ISSUE TITLE
Bot triggers on any word that matches

### ISSUE THREAD

**Issue by zaneneuschuler** [ace3df/AcePictureBot#70]
So, in discord the bot, instead of only triggering on the messages with only say "waifu" or "idol" on them, it triggers whenever that word is said in general. See attached.
![2016-06-16_19-50_1768](https://cloud.githubusercontent.com/assets/18064810/16139399/b75d2978-33fb-11e6-896f-b36a9c36d68b.png)

**Comment by ace3df** [comment]
No, this would be inconsistent with how it works on Twitter and other platforms.
If you wish for it not to trigger so easily get the server owner to do:
!apb mention on 

so users will have to @ mention the bot first.

or get the bot to ignore #general chats

https://gist.github.com/ace3df/cd8e233fe9fe796d297d#all-mods-can-do
