### ISSUE TITLE
Can't use the command mywaifu

### ISSUE THREAD

**Issue by ReapJacker** [ace3df/AcePictureBot#73]
Every single time I use "mywaifu" the bot doesn't give me anything, even though I have a waifu or a husbando registered.

**Comment by ace3df** [comment]
Are you not just limited? The bot has no reason to reply with nothing unless you're limited.

**Comment by ReapJacker** [comment]
Actually, I can't use any command right now, I'll just wait to register another waifu tomorrow or something :/

**Comment by thebestgusgus** [comment]
the command works fin on twitter however it keeps telling me to register on discord wheneve i try to use the command there
