### ISSUE TITLE
Warspite when

### ISSUE THREAD

**Issue by ghost** [ace3df/AcePictureBot#74]
There have been quite a few new ships for a few months now in Kancolle who have a big following, like Warspite who is missing. The Queen will not stand for this frenchness.

pls add

**Comment by ace3df** [comment]
I know about these new shipgirls and I always give it awhile before adding them to make sure there is enough fanart of them around. Right now they only have a small handful of (good) art. They'll probably be added next month along with new waifus and husbandos (this is all automatic now).
