### ISSUE TITLE
mywaifu doesn't work due to not having enough images

### ISSUE THREAD

**Issue by DinduNuffins** [ace3df/AcePictureBot#75]
On the list, Aoyama Nanami, but can't be used due to lack of pictures despite having quite a few on gelbooru. Not much else to say about it

**Comment by ace3df** [comment]
There are only 17 with the tags we use http://gelbooru.com/index.php?page=post&s=list&tags=rating%3asafe+1girl+solo+aoyama_nanami

You would end up going through all their images in just over a week. Not much more can be done.
