### ISSUE TITLE
"Invalid token!" while trying to connect to Discord

### ISSUE THREAD

**Issue by ghost** [ace3df/AcePictureBot#79]
Hi, 

I've changed my Twitter account for personal reasons and deleted my previous one. Yet I connected it to Discord's AcePictureBot. When I use "MyWaifu" on my discord server, I get a pic from the waifu I had on my previous account but not on the new one. When I run the "!apb info" and use "my ID" to connect my Twitter waifu to discord, I get an error : "Invalid token! Say MyWaifu on Discord to get your token!"

So my question is : is there a way to disconnect my discord account to the APB's waifu from my old twitter so that when I run MyWaifu I get a new "valid" token to reconnect it with Twitter without having to create a new Discord Account? 

Thanks in advance

**Comment by ace3df** [comment]
There is no way to disconnect right now because of possible abuse (I have a plan but nothing in yet)
If you post your "My ID:" part here I'll disconnect it for you.

**Comment by ghost** [comment]
Here it is : "Your ID: 223048058605273091"

Thanks
