### ISSUE TITLE
@AcePictureBot isn't replying

### ISSUE THREAD

**Issue by Nudgyy** [ace3df/AcePictureBot#80]
So, I tried tweeting WaifuRegister once and it said that they don't know the person. So I decided to change to another waifu, but this time the bot isn't replying.. And when I try to do the command in discord or twitter, nothing happens.. Help

**Comment by ghost** [comment]
Registering doesn't work on Discord, it has to be on Twitter. About the bot not replying, I think it's because the issue is the same as the previous one. 

Also I noticed sometimes the reply doesn't show itself in your notifications so check your Timeline.

**Comment by ace3df** [comment]
Probably got limited. Although now it should have cool downed. 
Check the examples here:
http://ace3df.github.io/AcePictureBot/commands/
