### ISSUE TITLE
I don't think the bot handles japanese discord nicks fine

### ISSUE THREAD

**Issue by OrdinaryMagician** [ace3df/AcePictureBot#81]
I can't remember if I reported this before, but I'm unable to link my twitter and discord because it asks me to tweet `@AcePictureBot connect discord d雨沙d1618390ci雨o`, which I do and doesn't work. And I have to wonder... is that id even correct or is it mangled because my name is 霧雨魔理沙?

**Comment by ace3df** [comment]
I've changed it so username wont be in tokens now. 
Use MyWaifu and you should be given a new token.
