### ISSUE TITLE
No DM link from Twitter to Discord

### ISSUE THREAD

**Issue by Cute-Saria** [ace3df/AcePictureBot#86]
I try to put the command Mywaifu on a server on Discord with the bot there and it doesn't show it instead responds with "I don't know who your Waifu is! Use WaifuRegister on Twitter or try saying 'Waifu'" but I already have a Waifu made on Twitter.

**Comment by ace3df** [comment]
Did you connect an account before?

If so please tell me your current Discord ID (using !apb info and copying "Your ID:") or giving me your old Twitter handle.

**Comment by Cute-Saria** [comment]
Saria#7305

**Comment by ace3df** [comment]
I need your actual user ID
In a Discord server that has AcePictureBot use: "!apb info" and copying "Your ID:"

**Comment by Cute-Saria** [comment]
274982709389033472

**Comment by vhantrec1** [comment]
How to connect to discord?
