### ISSUE TITLE
Invalid Token

### ISSUE THREAD

**Issue by akaarisu** [ace3df/AcePictureBot#88]
Hello,

I have added the AcePictureBot to an Discord server and gave all needed rights.
After saying 'MyWaifu' I also got a DM of the bot telling me to tweet a message: 
"Link your account by tweeting to https://twitter.com/AcePictureBot
@AcePictureBot connect discord TokenXY"

Easy as the instructions are I headed over to twitter, did that and just got the reply "Invalid Token, Please your MyWaifu to get your token". However since then I can't get a new token and the old one doesn't work anyway, would be nice to get some assistance with this.

**Comment by ace3df** [comment]
I will look into this today.
If possible please use "!apb info" and copy "Your ID: " at the bottom into here.

**Comment by akaarisu** [comment]
Sure, 
Your ID: 276815019512037377
if anything else is needed just let me know.

**Comment by ace3df** [comment]
That ID is already connected to the Twitter account (ID: 549899955) AkaArisuu
I've removed the connect so you can re-connect to another account if you so wish. 
It should work after that. Any other problems just say!

**Comment by akaarisu** [comment]
Great, it works perfectly now!
Weird it didn't before as it said it would be invalid. But anyway thanks for helping out this fast!
