### ISSUE TITLE
Register your Waifu using Waifu Register! (Discord)

### ISSUE THREAD

**Issue by dovdemoii** [ace3df/AcePictureBot#89]
Registered waifu on twitter and then got the token from discord and linked my twitter to my discord successfully but when I use the MyWaifu command on Discord, I get a prompt telling me to "Register your Waifu using Waifu Register!". Strange because the MyWaifu command works perfectly fine for me on twitter.

**Comment by ace3df** [comment]
I'll look into this
If possible please use "!apb info" and copy "Your ID: " at the bottom into here.

**Comment by dovdemoii** [comment]
My ID is 269964286988779521

Thanks for the response!

**Comment by ace3df** [comment]
I've fixed something that might have caused this. 
Try now!

**Comment by dovdemoii** [comment]
Yup it works now!
