### ISSUE TITLE
Invalid Token

### ISSUE THREAD

**Issue by ArsonistDave** [ace3df/AcePictureBot#90]
I had a husbando registered, but when I tried to use it today it didn't work, apparently my twitter account got suspended, and when I asked they immediately unsuspended it, maybe inactivity? Either way, that's beside the point, I can't use any commands, and it's telling me to link my account, but says "Invalid Token" every time I try... Thanks in advance!

**Comment by ace3df** [comment]
This usually happens if you already have an account link to another twitter.

In Discord use !apb info and copy "Your ID:" here.

**Comment by ArsonistDave** [comment]
166403228907470849
