### ISSUE TITLE
Unable to connect my Twitter account to my Discord

### ISSUE THREAD

**Issue by lemonteasour** [ace3df/AcePictureBot#94]
As mentioned in the title, I am having trouble connecting my Twitter account to my Discord one. Even though I inserted my token as instructed, the bot would reply with "Invalid token!"
Please look into it.
The Twitter status of my tweet for AcePictureBot: [here](https://twitter.com/maskedprayer/status/965841192406548480)
My ID (acquired through the command `!apb info` on Discord): 253495322125271041

**Comment by ace3df** [comment]
Request a new token on Discord and it should work now
